server:
  port: ${PORT:8080}
  address: 0.0.0.0
spring:
  docker:
    compose:
      enabled: false
      file: src/main/docker/compose.yml
      lifecycle-management: start_only

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/samurai
    username: samurai
    password: password


  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      show-sql: true
    properties:
      hibernate:
        default_schema: public



  liquibase:
    enabled: true
    change-log: db/changelog/master.yaml
  task:
    scheduling:
      enabled: true

  sonar:
    login: ${SONAR_PASSWORD}


